### ISSUE TITLE
\n symbol is parsed as a normal token

### ISSUE THREAD

**Issue by mkudinov** [zy4kamu/Coda#2]
Hi, there!
I decided to create an issue to make work on the project more transparent :)
We detected a bug in tokenizer/lemmatizer part

tokenizer = Tokenizer("RU")
disambiguator = Disambiguator("RU")
sentence = u'МИД пригрозил ограничить выезд \n американских дипломатов по России \n'
tokens = tokenizer.tokenize(sentence)
disambiguated = disambiguator.disambiguate(tokens)
for d in disambiguated:
    print(d.lemma)
    print(d.label)

----------------------------------
Output:
----------------------------------
мид
S@ЕД@МУЖ@ИМ@НЕОД
пригрозить
V@СОВ@ИЗЪЯВ@ПРОШ@ЕД@МУЖ
ограничить
V@СОВ@ИНФ
выезд
S@ЕД@МУЖ@ВИН@НЕОД

S@ЕД@ЖЕН@ИМ@НЕОД
американский
A@МН@РОД
дипломат
S@МН@МУЖ@РОД@ОД
по
PR
россия
S@ЕД@ЖЕН@ДАТ@НЕОД

S@ЕД@ЖЕН@ИМ@НЕОД

As you may see, two LF symbols were not filtered by tokenizer an then fed to lemmatizer. I consider it a bug. We, obviously, can fix it just by adding strip() to tokenize(). Or should we fix this on C++ part?

**Comment by zy4kamu** [comment]
Fixed. Just improved preprocessing of sentence in C++.
