### ISSUE TITLE
Input checking? 

### ISSUE THREAD

**Issue by GrachevArtem** [zy4kamu/Coda#7]
Hello! 

There isn't input checking. Probably, it should be added. 

```
from coda.tagset import Syntagrus2OpenCorpora

if __name__ == '__main__':
    converter = Syntagrus2OpenCorpora()
    tag_sr = u'S@МН@CЛЛЛ@ВИН@ОД'
    tag_oc = converter.convert_syntagrus_tag_to_opencorpora(tag_sr)
    print(tag_oc)
```

Output 

`>>  [u'NOUN', u'plur', u'accs', u'anim']
`

**Comment by mkudinov** [comment]
I decided to let all converters convert everything they can and no cause warnings or errors if they encounter unknown gram-code. We would discuss if we should emit warning in this case but now I would close this issue for better times :)
